### ISSUE TITLE
Git enhancements

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#100]
I've started a major overhaul of git. 
See    https://github.com/jsbain/stash/tree/safer

Right now, I have `git branch` completely rewritten, and it behaves (mostly) like the real git branch command.  It is now possible to create a branch from an existing start point (such as remote/branch), rename branches, delete local branches, delete local copies of remote tracking branches (in refs/remotes/), set or remove upstream ref for a branch (not yet used in push/pull, but will show the number of commits ahead or behind upstream when using git branch -v) and a few other improvements.

Since implementing full git code takes a lot of code, it is making more sense to break this into a separate .py file.  How would you like this organized?

Right now, I left `git.py` in `bin`, and placed my branch.py into `bin/git-scripts`.  I could see another option being to put the supporting scripts into `lib/git`.  What's your preference?

**Comment by dgelessus** [comment]
Placing git subcommands under `lib/git` seems more logical to me. `bin` is where the main executables go, anything they depend on should be placed somewhere in `lib`. That way `bin` also stays cleaner and we don't need to worry about possible issues with `bin` subfolders.

Being the conventionist (is that even a word?) person I am I'd even lean towards separating `bin` (core shell utilities necessary for basic use) from `usr/bin` (utilities that are technically not necessary or used by the shell itself) as is done on practically any modern Unix system. That should be discussed in a separate issue though.

**Comment by ywangd** [comment]
@jsbain My opinion is to store the sub-command scripts somewhere else other than `bin`. Scripts or folders inside `bin` are part of Tab auto-completion possibilities. So if you type `gi` then press Tab key, both `git` and `git-scripts` are shown in the candidate list. This seems to suggest that both of the commands are supposed to be called directly from command line. I do note that technically `git-scripts/git-branch.py` can be directly called, but it is probably not the recommended usage of this script. So if a script is by nature a sub-command, I'd suggest place it outside of `bin` and only leave the main script inside `bin`. The separation also leaves room for any future pure-helper scripts that are not possible to be called directly. It is also kinda a protection for a script because it does not lead users directly to the guts of a script (at least not from the Tab auto-completion suggestions).

`lib/git` looks good to me. I added `lib` initially for helper functions. But the sub-command scripts also seem to be a good use case of this folder.

**Comment by jsbain** [comment]
okay, `lib` it is!
