### ISSUE TITLE
problems with git

### ISSUE THREAD

**Issue by cjchallis** [ywangd/stash#113]
I just re-installed StaSh.  It had been working perfectly with git, but after reinstalling Pythonista I can no longer get it to work.  Upon installing StaSh and attempting a git command, it asks to download dulwich.  The only error I see during this is that it can't find `~/stash/lib/dulwich.old`.  Now all git commands result in `stash: <type 'exceptions.StopIteration'>:`.  Last time I installed shellista and the shellista-dev branch before installing StaSh.  I can't seem to duplicate however I had it working before - any suggestions?

**Comment by jsbain** [comment]
What version of stash are you using? Did you install from master, or dev?
 When did you reinstall  (there was a recent git update, though it shouldn't have affected the dulwich install)?

Do you respond "y" to download dulwich?  
Does it stop at the "can't find dulwich.old" or does it appear to install?
I'll take a look tonight to see if I can reproduce.

**Comment by jsbain** [comment]
set py_traceback=1 in _DEFAULT_CONFIG near line 1966, and paste the traceback of the error you are getting.  Maybe try restarting pythonista.  What device/os are you using?  Are you using the beta?

**Comment by cjchallis** [comment]
Thanks for looking into this so fast!  More details below:
Stash v0.4.1 from master.
Reinstalled 3/23/15, first install was probably 3/17/15.
Device: iPhone 5S, iOS 7.1.2
Yes, responded "y" to download dulwich.
Appears to install.  Doesn't ask to download dulwich anymore, just gives the `StopIteration` exception instead.
I tried restarting and even reinstalling pythonista.  

After writing the above, I set the py_traceback=1 and went to get the traceback, and of course it's working now.  My only guess is some kind of interaction with the shellista-dev-modular branch.  After posting the issue last night, I got git working in that again so that I could at least have the functionality there.  The first time I installed stash, I was using git in shellista-dev-modular as well.  It appears this may be necessary in my case to have git function correctly in stash? Whatever the case, it appears to be working again.  Let me know if you're still interested in figuring out what was happening.

**Comment by jsbain** [comment]
To clarify... when you installed shellista (dev-modular) and used git, stash git started working?  
Or when you were using shellista's git, that caused the StopIteration?

Both shellista git and stash git depend on dulwich, gittle, and funky.  If you've run shellista before stash (without restarting pythonista), the imports are the same, and there may be some incompatibility.
Currently, you can use the stash version with shellista, but in the future this might not be the case, as I'd like to eventually move over to an unpatched dulwich.

I *thought* I had handled the various cases of this (I try to unload dulwich, then reload the copy inside the stash/lib folder), but trying to unload a module might not always work.  If you are telling me that, after running shellista, stash git fails, I could perhaps understand that.  If you are telling me that you have to first run shellista, to get stash to work, I'm very surprised.


--------------------------------------------
On Tue, 3/24/15, cjchallis <notifications@github.com> wrote:

 Subject: Re: [stash] problems with git (#113)
 To: "ywangd/stash" <stash@noreply.github.com>
 Cc: "jsbain" <jsbain@yahoo.com>
 Date: Tuesday, March 24, 2015, 5:43 AM
 
 Thanks for looking into this so
 fast!  More details below:
 
 Stash v0.4.1 from master.
 
 Reinstalled 3/23/15, first install was probably 3/17/15.
 
 Device: iPhone 5S, iOS 7.1.2
 
 Yes, responded "y" to download dulwich.
 
 Appears to install.  Doesn't ask to download dulwich
 anymore, just gives the StopIteration exception
 instead.
 
 I tried restarting and even reinstalling pythonista.  
 
 After writing the above, I set the py_traceback=1 and
 went to get the traceback, and of course it's working
 now.  My only guess is some kind of interaction with the
 shellista-dev-modular branch.  After posting the issue last
 night, I got git working in that again so that I could at
 least have the functionality there.  The first time I
 installed stash, I was using git in shellista-dev-modular as
 well.  It appears this may be necessary in my case to have
 git function correctly in stash? Whatever the case, it
 appears to be working again.  Let me know if you're
 still interested in figuring out what was happening.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by cjchallis** [comment]
All I can say for sure is that both times I got git working with Stash, I already had it running correctly in shellista-dev-modular.  It's fairly likely I was making some other stupid mistake, so I wouldn't look any more into this unless it crops up again.  If I ever need to reinstall, I'll pay careful attention to see if I can duplicate the error.
