### ISSUE TITLE
Doing `selfupdate` and the `version` shows the old version number

### ISSUE THREAD

**Issue by cclauss** [ywangd/stash#114]
Doing `selfupdate` and the `version` shows the old version number until you rerun stash.

**Comment by ywangd** [comment]
If `stash.py` file is changed by `selfupdate`, the changes won't take effect until StaSh is restarted. The `version` variable is unfortunately part of `stash.py`, that's why the new number won't show up until rerun. 

I am not sure if it is possible to completely reload StaSh programmatically after `selfupdate`, especially when there is no way to programmtically close a panel UI. So for now, I guess a manual restart is unavoidable.

**Comment by oefe** [comment]
Maybe change the "Done" message to something like "Stash was updated successfully. Please restart stash for the changes to become effective"?

**Comment by ywangd** [comment]
@oefe That is probably a good idea. I'll make the change. Thanks!

**Comment by ywangd** [comment]
44c7707b5fbe7b5b3dc241991b8eb046db3fca83
