### ISSUE TITLE
clearing globals breaks stash

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#122]
clearing globals, when running another script in the beta for example, clears references to modules, and stash breaks.   the fix is a launcher which imports stash, that way all needed references are stored locally within the module.  

the following `launch_stash.py` seems to survive global clear.  possibly we may want to keep the instances in an array, rather than overwriting, to allow multiple sessions, or have some sort of module method that checks/returns the one instance, to sllow easy recovery from global clearing.

```python
import stash
_stash = stash.StaSh()
_stash.run()
stash._stash=_stash
```

**Comment by ywangd** [comment]
The launcher script does allow stash survive through global clear, though I don't quite understand how it could work. The global clear cleared everything including the stash module. But maybe only the reference is removed and the actual module still exists because a running UI is referring to it?

In version 1.5, we have the option to turn off global clear but it does not seem to be available in 1.6 (I just got 1.6 two days back so correct me if I am wrong). 

Is it somehow possible to blend in the launcher script into the main stash.py file? If not, I'll just add the launcher as suggested. Thanks!

**Comment by dgelessus** [comment]
The "clear globals" thing does exactly what it says - it deletes all globals (except for a few things like `_outputcapture`, `_importcompletion` and `sys`, because Pythonista needs those). However it doesn't reload any of the modules and doesn't clear `sys.modules`. This means that all module attributes (like `stash._stash`) are kept, even though there is no global reference (`stash`) to the module.

**Comment by jsbain** [comment]
The interpreter caches modules, even though globals are cleared.  So although `stash` no longer appears in the console, sys.modules['stash'] still exists.  My thought of putting _stash into the module ensures that later, you could get access again by doing `import stash; _stash=stash._stash`.  It might also be possible to have stash runtime check for `_stash` in globals, and if it has been cleared, then re-set it... but i haven't tried yet. 


     On Sunday, July 26, 2015 6:27 AM, dgelessus <notifications@github.com> wrote:
   

 The "clear globals" thing does exactly what it says - it deletes all globals (except for a few things like _outputcapture, _importcompletion and sys, because Pythonista needs those). However it doesn't reload any of the modules and doesn't clear sys.modules. This means that all module attributes (like stash._stash) are kept, even though there is no global reference (stash) to the module.—

**Comment by ywangd** [comment]
I did a bit more test and found the launcher code can be embedded into the main `stash.py` file as follows:

```Python
...
if __name__ == '__main__':
    if 'stash' in sys.modules:
        stash = sys.modules['stash']
        reload(stash)  # reload to ensure any changes to be honoured 
    else:
        import stash

    ... # command line option handling

    stash._stash = _stash = stash.StaSh()
    _stash.run()
```

Thoughts please?

**Comment by dgelessus** [comment]
@ywangd, `import stash` will always use `sys.modules["stash"]` if it exists. No need to manually do that.

**Comment by ywangd** [comment]
@dgelessus You probably misread the code. The code `import stash` if it does NOT exists and `reload` if it exists. The reload is to make sure any modification to the file takes effect after close and relaunch.

**Comment by dgelessus** [comment]
I should've been more clear - what I meant was that because `import` will always pull from `sys.modules` if possible, you could simplify the `if` block as

```python
import stash
reload(stash)
```

The extra `reload` doesn't do any harm even if the module wasn't in `sys.modules` before.

**Comment by ywangd** [comment]
I didn't simply use `import` along with `reload` because it will load the module twice if the module does not exist in `sys.modules` (first import then reload). I do realise this is only a minor optimisation.

**Comment by ywangd** [comment]
Somehow it has to be a separate launcher file to work with version 1.5, while it is alright to mix the launch code in the main file in 1.6 beta. No idea why.

I have added the launcher file (see 1eb2a673ca441b6773bb1457820fbe9529c75b88). Thanks @jsbain

**Comment by GeorgViehoever** [comment]
Should this be closed?

**Comment by ywangd** [comment]
Made a bit more changes to the launcher script: 
* Take care of reloading
* Multiple StaSh instances are now isolated from each other (Pythonista 1.6 only)

9f75b5267e90d4d47f2d7b252a7635078f136c60

**Comment by ywangd** [comment]
@jsbain @dgelessus 
With the latest Beta 160033, even the launch script cannot help StaSh survive through the global variable clearing. Any suggestions? Do I have to rely on the new `pythonista_startup.py` file?

I am working on a version using the new objc stuff and the global clearing not only breaks the shell but crashes the entire app ...

**Comment by dgelessus** [comment]
Yes, Pythonista now automatically reloads any user modules (i. e. anything from the Script Libary/`~/Documents` except `site-packages`). My [ugly hack](https://forum.omz-software.com/topic/2175) to preserve globals doesn't prevent this either, because module reloading is done by iterating over `sys.modules`. For now you could move `stash` into `site-packages`, this should make the auto-reloader skip it.

**Comment by jsbain** [comment]
couldnt we also rename _stash to __stash?  that will allow the global to survive.  though if sys.modules get cleared, will that break running code?

As another option, could we import pythonista_startup, and if it exists, add the stash module to the pythonista_startup in memory?   And if not, create an entry in sys.modules for it (i.e dynamically create a module)

**Comment by ywangd** [comment]
So far placing stash inside site-packages seems to be the most reliable way to avoid it gets flushed by the global clearing event. This essentially requires stash to become a package and I did that by simply adding a `__init__.py` file in the top level directory. Just renaming `_stash` to `__stash` did not work and I am not sure why.

**Comment by dgelessus** [comment]
The reason why stash is reset is because all its modules are reloaded unless it is in `site-packages`. The global `_stash` being deleted is not the problem.

**Comment by ywangd** [comment]
StaSh for Pythonista 2.0 is now installed inside `site-packages`. So I assume global clearing is no longer an issue.
