### ISSUE TITLE
consider using on_main_thread for flush

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#126]
i suspect the reason we had to flush multiple times was because we didnt run on the main thread.  obviously this decorator is only available in the beta, but might be worth trying in your redesign.

also, another possible issue : i think you are using ui.in_background to run the pipe.  i have observed that ui.in_background does not start a new thread, but instead queues commands onto a single background thread.  as a reuslt, there may sometimes be a longer delay than might otherwise be expected, for instance if calling another ui backgrounded call from within an already backgrounded call, the second call doesnt execute until the first function exits.   i think your sh_background is more robust.

**Comment by ywangd** [comment]
I'll definitely try `on_main_thread` when it comes to the scrolling. Now I am still trying to figure out the higher level structure of the re-design. Ideally to have more modular components and better interfaces. It turned out to be quite tough.

As for `ui.in_background`, I only use it to run commands that explicitly require to run in background (with the ampersand suffix), e.g. `some_script.py &`. This is because I have no good way to terminate a regular background thread, but the `ui.in_background` runs in the same thread as the interactive prompt so it can be nicely stopped by tapping the "X" button, for which Pythonista raises `KeyboardInterupt` to the running thread and allow it shutdown nicely (releasing resources etc.)

I did notice tasks are queued automatically by `ui.in_background` and there are comments about it in the README file.

**Comment by ywangd** [comment]
This is now the case in the new beta16 branch. No more delayed and repeated scrolls.
