### ISSUE TITLE
entered a picture(png) as a command 

### ISSUE THREAD

**Issue by himehowareu** [ywangd/stash#137]
![image](https://cloud.githubusercontent.com/assets/4483333/9940232/2a21eb82-5d34-11e5-93ef-891444dfdbfd.png)
Not sure what happened but i was playing with your terminal, well done ( i was working on something like this for pc and your is way better dice job) .

**Comment by ywangd** [comment]
I am not sure how exactly did you *entered a picture as a command*. Did you do it programmatically? I think it resulted in binary data of the png file being passed through. These binary data cannot be decoded to Unicode values because they are NOT meant to be human readable. 

The `UnicodeDecodeError` error happened when a Byte string cannot be decoded to Unicode using `utf-8` codec. Try `'\x89'.decode('utf-8')` on a Python prompt, you'll get the same error. The correct encoded string in this case should be `'\xc2\x89'.decode('utf-8')`. But again since the binary data are not meant to be human readable, it is semantically wrong to attempt decoding them.

So the quick fix would be avoiding pass binary data to the Shell. I'll also think about adding an error handler to report this type of error in a less intrusive manner.

Thanks!

**Comment by himehowareu** [comment]
I 'cd'ed to a folder that had a picture in it. Then I simply typed the name of the picture as input to the prompt

**Comment by ywangd** [comment]
OK I get it. Currently if a file is not a Python code (`.py` files), stash will try to run it as a shell script. In your case, the shell took the png file as a shell script and tried to parse its binary content.

This is indeed a bug and I can reproduce it. I'll add more checks to avoid parsing binary files. Thank you!

**Comment by ywangd** [comment]
It is now fixed e2fefdb4d19b63d6962de9c54a3efc80be954e3d
Please run `selfupdate` from within the shell to get the latest changes.

Thanks again for reporting the issue.

**Comment by himehowareu** [comment]
Ok thank you for your quick response. 
You do good work keep it up .
