### ISSUE TITLE
dev maximumrecursion

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#157]
when running, e.g git branch, I had a call like this:

``` 
  _stash.runtime.exec_py_file(cmdpath, args=args,
	                     ins=sys.stdin, outs=sys.stdout, errs=sys.stderr)
``` 
which reults in a maximum recursion depth.  I set a trace before this line, and stepped through, and the offending line seems to be:

``` 
>/private/var/mobile/Containers/Shared/AppGroup/C534C622-2FDA-41F7-AE91-E3AAFE5FFC6B/Documents/site-packages/stash/system/shruntime.py(440)exec_py_file()
-> current_state.sys_stdin = ins
(Pdb) n
>/private/var/mobile/Containers/Shared/AppGroup/C534C622-2FDA-41F7-AE91-E3AAFE5FFC6B/Documents/site-packages/stash/system/shruntime.py(442)exec_py_file()
-> if outs:
(Pdb) stash: <type 'exceptions.RuntimeError'>: maximum recursion depth exceeded
``` 

This problem occurs in dev 9a1b693f00dd0400d2e46bd6c1953ae72494bb4d

**Comment by ywangd** [comment]
This is now fixed with latest commit 02f8a50a5a01f1c0d9db3ecc518a347c1c583933

Basically it is now required to use the StaSh callable interface to run commands. So the change is to replace `_stash.runtime.exec_py_file(...)` with the followings
```python
_stash(cmdpath + ' ' + ' '.join(args))
```

This callable interface does extra housekeepings for running commands, e.g. taken care of IO dispatching.
