### ISSUE TITLE
`help` will print *.py files under ~/Documents/bin

### ISSUE THREAD

**Issue by wizardofozzie** [ywangd/stash#160]
I'm not great with debugging, but I'll do my best here.

Basically, I had a directory structure as so:

`~/Documents/bin/remove_metadata.py`
`~/Documents/bin/noop.py`

Then, when I go into stash and type `help`, the help messages would print up until `rm`, but it would also list `noop` in the help commands.

So basically, stash is reading the wrong `bin` directory (instead of `~/Documents/site-packages/stash/bin`, it's also reading `~/Documents/bin`

I solved the issue by moving any `*.py` files from under `~/Documents/bin`

[Error screen paste](https://gist.github.com/anonymous/7972c6f56bc7570b1c8e)

**Comment by ywangd** [comment]
Both `bin` directories are by default the locations where StaSh searches for command scripts. This is intentional as it is recommended to place user scripts under `~/Documents/bin/` so they do not interfere StaSh's internal `bin` (`~/Document/site-packages/stash/bin/`) but can still be called from StaSh's console.

With above said, you are right that the `help` command should only look into the internal `bin` folder. It can only hope sensible help messages to be generated for builtin commands NOT user scripts. It should not assume user scripts to follow a certain format or even complete. I'll make the change.

Thanks!

**Comment by wizardofozzie** [comment]
Yeah, in the cases where there are no help docs there's no issue with the parsing, since it lists the file name (command) only.
Thanks again!

**Comment by ywangd** [comment]
This issue is fixed with commit 29ff695934719e03178ead05e60e2d558e873924
It is currently available in the `dev` branch and will be merged to `master` soon.
