### ISSUE TITLE
SystemExit not caught

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#163]
I believe 
            except Exception as e:
should be
             except BaseException as e:
so that systemExit exceptions are caught.  Or, else handle SystemExit specifically.

I am using a library (docopts) which calls SystemExit, or a subclass thereof, to set a message and exit code.  Not sure how common this is,  but seems like stash should handle this.

**Comment by jsbain** [comment]
hmm, i tried catching SystemExit in shruntime.run(),  and it was never caught. Thoughts?  zis this getting filtered elsewhere? or does pythonista not pass this error?  I can catch it in the console.

**Comment by ywangd** [comment]
The SystemExit exception is handled in `ShRuntime.exec_py_file`. This is because `ShRuntime.run` can take a series of commands with each command being a python file, e.g. `wget FILE.zip; unzip FILE.zip; ...` or multiple lines of commands like a shell script. Each of these command can possibly raise a `SystemExit` and they all should be handled separately. That is why they are handled in `exec_py_file` as it runs only one command at a time. This also ensures that if some command raises `SystemExit`, it does not stop following commands from running. 

Some of the existing commands are already issuing `SystemExit`. For an exmaple, `cat` calls `sys.exit(0)` when everything is OK but calls `sys.exit(1)` for errors (e.g. file not found). 

I believe `argparse` raises `SystemExit` as well and it works with stash. Is there something not working right with `docopts`?

**Comment by ywangd** [comment]
[This is the line](https://github.com/ywangd/stash/blob/dev/system/shruntime.py#L472) where `SystemExit` is handled

**Comment by jsbain** [comment]
turns out there was some strange formatting in the docstring i was working, and docopts using SystemExit made it hard to debug, since things just failed silently.  For some reason I was thinking that SystemExit with an abnormal code would/should display something to the screen, similar to the way KeyboardInterrupt is handled, but  in retrospect this is not how it would be done in regular shell.
