### ISSUE TITLE
[idea] mount command

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#167]
I am not sure how this would work exactly, but seeking ideas.

it would be convienent to have a "mount" type command for attaching external file systems into stash.  Think dropbox, google drive, github, webdav, samba, etc...   We would create a set of "device drivers" which implement common file and folder ops, such as open, read, write, listdir, rmdir, mkdir, mv, cp, fstat, and a few others.  Then after mounting, stash would keep track of mounted drives, and any file ops using those paths would get farmed out to the "driver".   Ideally it would be neat if any script that uses the os or shutil libraries somehow would work out of the box, but that probably requires great feats of monkey patching which maybe we don't want.  An alternative would be to rewrite all supported commands in stash to make use of special stash "devices".

thoughts?

**Comment by ywangd** [comment]
Yes ideally it would be great if the `mount` command can work like its true counterpart so that other commands can work without changes. But it is probably very difficult if not impossible. Two possibilities are:

1. Using `ctypes`, it seems that we have access to libc's mount function (`ctypes.CDLL(None).mount`). But I haven't tested it and not sure if it is possible with iOS. However, even this allows mount of some NSF drive or even Samba, I don't see how Github repo can be mounted (which is likely the main use case for this command).

2. Monkey patch relevant Python libraries. I would not recommend this approach as it is difficult and result is likely to be suboptimal. There are some cases that the patch just won't work. For an example, if a module is imported already before stash runs and it has an import like `from os import listdir`, the monkey patch afterwards won't be able to help here as the module saves its own copy of listdir. Thus this module remains unaware of the "device drivers". There may be some convoluted way to fix this with the `gc` module (search for `listdir`'s reference and modify them). But it feels too hacky and unstable to me. (I tried something along this direction when working on allowing parallel running scripts each has its own copy of `sys.argv`. But the result was always a mess).

If we cannot take any of above approaches, we are not able to make "native" device drivers. So we'll have to either:

1. Rewrite all relevant stash commands. I am a bit hesitate about this option. This requires not only rewriting of many commands but also stash now has to actively tracking the status of all mounted devices. 

2. Create specific command for each type of device drivers, e.g. `gh` can be used for github repos. So you use it like `gh mount owner/repo`. Or you can have `gh` enters an interactive mode after mounting. Something like the FTP sesssion, for an example:

```bash
[stash]$ gh mount owner/repo
mounting owner repo ..
[(gh)owner/repo]$ ls
remote_dir/
remote_file_1.py
remote_file_2.py
[(gh)owner/repo]$ cd remote_dir
[(gh)owner/repo/remote_dir]$ lls
local_file_1.py
local_file_2.py
[(gh)owner/repo/remote_dir]$ get remote_file_1.py
Downloading remote_file_1.py ...
[(gh)owner/repo/remote_dir]$ unmount  # or exit/logout
bye ...
[stash]$ ls
local_file_1.py
local_file_2.py
remote_file_1.py  # this file is what just get downloaded from the repo
```

**Comment by jsbain** [comment]
does stash allow calling a function with a globals replacement?  I would hate to rewrite every command as a subcommand, as that would be a lot  of duplication and maintenance.  i am thinking of using subcommands, but where the subcommands call the existing stash ls, cd, etc, but with a shadow_os, shadow_shutil, etc, where these would be custom modules which override a few key methods to dispatch either to original os, or to a special version.

**Comment by dgelessus** [comment]
This "mounting" idea got me thinking a little as well. The two approaches that I think would be feasible are:

1. A module called e. g. `fake_mount` that provides all mount-related facilities, and a script to monkey-patch all built-in filesystem-related functions to work with fake mounts. This script would need to be called from `pythonista_startup` to work correctly. There are of course edge cases where fake mounts will not work, notably anything done from (Objective-)C code.
2. Something like `git clone`/`git push` in a more generic form. One command to download files from a remote location onto the device, and another one to upload changes back to the remote location. This is of course not practical for large amounts of data, but it would be guaranteed to work in all cases as real files are used.

**Comment by jsbain** [comment]
It is not obvious that we would need to do someing in startup.  Consider the following code which mocks `os`, then cleans up after execing the script.  I think as long as all mocked functions behaved normally when given valid arguments, and just acted special for specific file prefixes that get registered, it seems like this would be safe.  I think stash maybe installs a custom systrace, so not sure how that would work... but as long as we are not tracing the lines in stash brtween popping the module and replacing it, not sure what could go wrong,other than the usual dangers of  monkey patching.

``` 
# coding: utf-8
import imp,sys, os
_mod=sys.modules.copy()
sys.modules.pop('os')
newos=imp.new_module('os')
for k,v in os.__dict__.iteritems():
	newos.k=v
newos.__file__='this is a custom file'
def ld(pth):
	print 'replacement listdir'
newos.listdir=ld

sys.modules['os']=newos
try:
	g=globals().copy()
	exec('from os import listdir; print listdir("."); import os; print "os is now", os.__file__',g,g)
finally:
	sys.modules.pop('os')
	sys.modules['os']=_mod['os']
	import os
	print 'os is now',os.__file__
```

**Comment by jsbain** [comment]
Okay, this method does not replace existing module's imported modules... so os imports posixpath, if we mock posixpath os.path still points to the original.  That makes it harder to handle any arbitrary script, but for the basic file operations, ls, cd, cat, cp, mv ,rm, etc, there is a very small subset of os, shutil and a few others that need to be handled.  I am not sure if this is more or less work than basically copying all of those commands into subcommands.

**Comment by ywangd** [comment]
@jsbain Currently stash does not have the option to accept global replacement from the callable interface. But it is easy to add it if necessary. The script is executed with form of `exec(file, namespace, namespace)` and this is where global replacement can easily come in.

**Comment by ywangd** [comment]
@jsbain The problem you had with existing module caching its imports is exactly what I encountered before when trying to make each script have its own copy of sys.argv. Simply swap out a module in sys.modules is not enough and is very easy to break.

Above monkey patch also causes problems for parallel running scripts. Since we really just have one namespace (single process), if you patch `os.listdir` while a script is running, it will affect the running script as well. For an example, I have `httpserver.py` running as a background job and it imports `os`. Now `os.listdir` gets patched. Suddenly the httpserver script will mis-behave and list the github contents instead of local device ... 

I personally really think sub-command is a better approach. It may be dull compared to how fancy one can get with monkey patch and stuff. But it is much more reliable and predictable. Moneky patch is cool but is likey to suddenly fail because of unexpected usage.

**Comment by ywangd** [comment]
@dgelessus I believe the startup file is called as a last step of the startup process. In this case, many modules are probably already initialized and cached their copies of os and sys. And this will causes problems that @jsbain described. Also it will not work for all cases like you said. Also I think it is probably asking too much for users to modify their startup file. What if the code has some bugs and causes the whole App fail to start? I understand the problem can be solved via URLscheme. But still kinda pushing the limit ...

**Comment by bennr01** [comment]
Would it be possible to overwrite __bulitin__.__import__ for stash to return a fake-module-object using threading.local for thread-specific namespaces? If that would be possible, each thread would have its own copy of os and posixpath, making monkey-patching thread-safe. It would also make it possible to simple import a module replacement for mounted paths. (Sorry for my bad english, i hope you understand what i mean)

**Comment by ywangd** [comment]
@bennr01 `threading.local` is something that I haven't though about before. Thanks for the new tip. It will possibly solve the example issue that I raised for parallel running scripts. However it probably still won't help for existing modules caching its own copy of imports, i.e. the issue @jsbain had, unless we can replace `__builtin__.__import__` before any other python module gets loaded. I haven't tested it, may be @jsbain can verify it?

Another concern is that the faked module is no longer a module type (`types.ModuleType`) but an instance of `threading.local`. I am not sure if this could have any implications to other 3rd libraries.

**Comment by bennr01** [comment]
@ywangd according to the docs, `__import__` is also called for already imported modules (no module caching). If i understand this right, it means that later `import`-statements would use the `__builtin__.__import__`-replacement for already imported modules (I havent tested it).
Using `threading.local` directly may not work, but a custom class using `threading.local` with `__getattr__ and __setattr__` may work. This class could also subclass `types.ModuleType`.

**Comment by ywangd** [comment]
@bennr01 You are right that `__import__` is called even for already imported modules. I think I have tried this before and gave up because of nested imports, i.e. A imports B and B import C and my main program is M that imports A. But maybe I didn't do it right ... I need more time to think about this. Thanks!

**Comment by dgelessus** [comment]
Things are a lot easier if you don't replace modules in `sys.modules`, but instead only change their attributes. That way all module references remain intact and all code uses the updated versions (unless `from`-`import` was used).

The reason why I am suggesting a `pythonista_startup` hook is that at that point you can know for sure which modules have already been imported and may need patching. After the attributes have been patched, all future code will use the patched versions, even with `from`-`import`.

**Comment by bennr01** [comment]
@dgelessus thread-local states would make the monkey-patching more secure. Otherwise, a script could modify the custom `os`-replacements (e.g. `mount` adds a new ftp session to a path and overwrites `os`, but later a other script overwrites `os.listdir`, messing up the commands). Using thread-local module replacements would sandbox the scripts and commands, making parallel running of scripts and monkey-patching thread-safe (It would make the monkey-patching solution for `mount` easier and may fix `sys.argv`). The mounts would still be aviable for all commands.

**Comment by dgelessus** [comment]
Oh, you mean applying the mount patches globally, but letting commands run from stash only access thread-local copies of the modules? That does sound useful.

**Comment by jsbain** [comment]
My thinking is it would be too hard to find something that works for any possibly script usage -- so startup makes me nervous that it will be too hard to test.  But, if w focus on the specific dozen or so calls used by the main stash file ops, and perhaps input/output redirection operators, it becomes a mor contained problem. Nested imports could be handled on an ad hoc basis (i.e we figure out which methods we are using and which need to change).  

I suppose another approach would be to use a trace method which detects certain calls, and hijacks them?
