### ISSUE TITLE
stash losing control of stdout

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#177]
In the latest beta, with stash 0.6.5 (master), it seems that typing in the console causes stash to lose control of stdout--output is redirected to the console instead of the stash window.  

I don't quite follow where the stdout is set in the first place, so I have not been abe to debug.

**Comment by ywangd** [comment]
Each running thread (i.e. command) has its own `stdout`. It is attached to the thread object and can be accessed like `thread_obj.state.sys_stdout`. To make this work, a proxy object is used to replace (monkey patch) the pythonista wide `sys.stdout`. The object is called `ShStdoutWrapper` and can be found under `system/shiowrapper.py`. Basically what this object does is to check the thread when it is called, if the thread is a `ShThread` type, it redirects the call to the thread's `sys_stdout` property. Otherwise, it passes the call to pythonista default stdout. For an concrete example, the following sequence happens when stash starts:
 1. Set sys.stdout = stdoutWrapper
 2. Running command `ls`. This means a ShThread object is created to run the command and the thread's `state.sys_stdout` property is set according to how the command is invoked. For an example, the simplest form `ls` will just set `state.sys_stdout` to stash screen, i.e. `shio`. `ls > somefile` will set stdout to a file object. And `ls > &3` will set stdout to pythonista console.
 3. The thread running `ls.py` invokes a `print` call and this means `sys.stdout.write` is going to be called. 
 4. Since the `sys.stdout` is now stdoutWrapper, when stdoutWrapper receives the call, it checks the thread and sees it is a ShThread. So it retrieves the thread's `state.sys_stdout` object and pass the attribute access call to it, i.e. it will call `getattr(thread_obj.state.sys_stdout, 'write'). 

The above process exists to enable multiple commands running at the same time without interfere each other, e.g. one command can print to pythonista console and the other can print on stash screen.

In the recent beta, there must be some change that Pythonista will reset `sys.stdout` every time you use the console. Since stash only does monkey patch (https://github.com/ywangd/stash/blob/master/stash.py#L84) when it first launches, when the console resets it, stash loses the proxy object and this causes all output to simply goes to the console.

**A potential fix is to re-moneky-patch every time when a command is about to run**. This is easy to do, just call `enable_io_wrapper()` , possibly right before [this line](https://github.com/ywangd/stash/blob/master/system/shruntime.py#L314).

However, if you use console when the command is running, it will still affect the command's output destination. I am not sure what can be a proper fix for this situation. Maybe something along the thread locals as suggested by @bennr01 in issue 167 ?

**Comment by jsbain** [comment]
Yes, i think latet beta must be resetting the stdout -- it references the main stdoutcatcher, rather than the shiowrapper.  Although it always is the same object, so the actual object is not getting recreated, but the reference is getting updated.  

When switching to console while a script is running, I also get a repeatable crash.  I posted a question on the forum, though have not gotten a response yet.

**Comment by ywangd** [comment]
It would be great if omz provides an official hook mechanism for the
StdoutCatcher object so that monkey patch is not necessary. I did worry
about that the monkey patch would easily break. But there seem to be no
other way to achieve what I want.

On Saturday, 21 May 2016, jsbain <notifications@github.com> wrote:

> Yes, i think latet beta must be resetting the stdout -- it references the
> main stdoutcatcher, rather than the shiowrapper. Although it always is the
> same object, so the actual object is not getting recreated, but the
> reference is getting updated.
>
> When switching to console while a script is running, I also get a
> repeatable crash. I posted a question on the forum, though have not gotten
> a response yet.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ywangd/stash/issues/177#issuecomment-220758452>
>


-- 
----------------------------------------------------------------------
                      Life is elsewhere

**Comment by jsbain** [comment]
Have you tried monkey patching the _outputcapture methods?  Or monkey patching the actual StdOutCatcher write, etc methods?  I noticed the object does not change, so maybe that could work (I am on a slow connection right now, the new beta is still downloading, so i cannot test)

**Comment by ywangd** [comment]
hmm I haven't tried but monkey patch the `write` method of stdoutCather might work. I doubt it would do any good to patch _outputcapture as it is likely that its methods are cached by other modules already. 

However there are two concerns that I can think of right now:
 * It would be difficult to implement output redirect to console (i.e. `> &3`). A naive implementation will cause infinite recursive loop.
 * The approach may be too hacky and easily break in future betas?

**Comment by jsbain** [comment]
Ahh, ok.  I installed a fake sys to capture `__setattr__ ` to see who was setting stdout (i could not reproduce the behavior manually)
Turns out new versions of pythonista are calling will_close whenever we switch to console.... here is the stack trace of where stdout is reset:

``` 
  File "/private/var/mobile/Containers/Shared/AppGroup/C534C622-2FDA-41F7-AE91-E3AAFE5FFC6B/Documents/site-packages/stash/system/shui.py", line 291, in will_close
    self.stash.cleanup()
  File "/private/var/mobile/Containers/Shared/AppGroup/C534C622-2FDA-41F7-AE91-E3AAFE5FFC6B/Documents/site-packages/stash/stash.py", line 213, in cleanup
    disable_io_wrapper()
  File "/private/var/mobile/Containers/Shared/AppGroup/C534C622-2FDA-41F7-AE91-E3AAFE5FFC6B/Documents/site-packages/stash/system/shiowrapper.py", line 59, in disable
    sys.stdout = _SYS_STDOUT
``` 

I will post a bug report on the forums... in the meantime, it might be worth disabling will_close.

**Comment by ywangd** [comment]
Thanks a lot @jsbain 

I added a [condition check](https://github.com/ywangd/stash/blob/dev/system/shui.py#L291) so that the cleanup will not run for beta versions higher than 300010.

**Comment by ywangd** [comment]
The latest beta fixed this bug. So I reverted the changes to `will_close()`. All the changes are now pushed to the `master` branch.

This is all good for now. I am still thinking if there is a better way than the monkey patch. So please let me know if you have any new ideas. For now, I am closing this issue. Thanks!
