### ISSUE TITLE
CC crashes Pythonista

### ISSUE THREAD

**Issue by glider-gun** [ywangd/stash#186]
On Pythonista 3.0, CC (Ctrl-C) crashes Pythonista App itself.
for example, interrupting `python` command by CC crashes Pythonista.

This doesn't occur for Pythonista 2.1.

**Comment by ywangd** [comment]
Bummer. Pythonista 3 crashes on many ctypes calls and this is one of them. It is probably due to the dual interpreter change. I am not quite sure. 

Anyway, a workaround is available, add following content in `.stash_config` or `stash.cfg` file under stash installation root:
```
[system]
thread_type=traced
```

If the file does not exist, just create a new file for it. The downside of this change is mainly performance. It is about 2-3 times slower than the default `ctypes` thread. But for most commands, the difference is not too noticeable.

**Comment by glider-gun** [comment]
I see. Thank you for the workaround, it worked.

**Comment by ywangd** [comment]
The bug is now fixed. You can get the updated version via `selfupdate` and remove the `thread_type` config. Thanks!

**Comment by glider-gun** [comment]
Thank you!
