### ISSUE TITLE
Pip recently stopped working

### ISSUE THREAD

**Issue by chibill** [ywangd/stash#191]
Trying to pip install any file responds this error.

stash: <class 'xmlrpclib.ProtocolError'>: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>

**Comment by chibill** [comment]
Well git messed up the error here it is. 

> stash: <class 'xmlrpclib.ProtocolError'>: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>

**Comment by chibill** [comment]
`stash: <class 'xmlrpclib.ProtocolError'>: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>
`

**Comment by ywangd** [comment]
This has been fixed a while back. Please update to the latest version with
`selfupdate` and restart Pythonista.

On Sunday, 10 July 2016, William Gaylord <notifications@github.com> wrote:

> stash: <class 'xmlrpclib.ProtocolError'>: <ProtocolError for
> pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ywangd/stash/issues/191#issuecomment-231560461>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACPFdE-bCawKZ-QfZ6FUgQCQdUfKL4XKks5qUCfSgaJpZM4JIuFp>
> .
>


-- 
----------------------------------------------------------------------
                      Life is elsewhere

**Comment by chibill** [comment]
I have. But it keeps being version 0.6 8

**Comment by chibill** [comment]
Also I am on pythonista 3

**Comment by ywangd** [comment]
Did you restart Pythonista, i.e. double click the Home button and swipe up to remove Pythnoista out of the task list?

**Comment by chibill** [comment]
Yes I have even tried restarting my whole iPad. I am going to try
reinstalling stash next.

**Comment by ywangd** [comment]
In that case, you must have multiple instances of StaSh installed in your system.

StaSh installs itself into `site-packages`. But you probably have a version installed in `site-packages-2` as well and it will not be updated by the `selfupdate` command. If you type and run `which pip`, what output do you see? On my device, it says `~/Documents/site-packages/stash/bin/pip.py`

Strictly speaking, stash is a Python 2 module and thus fits in `site-packages-2` directory. However, it's default behavior always uses `site-packages` and I don't want to change it exactly because of this multiple installation issue. Plus once it is migrated to be an universal 2 and 3 module (which will happen eventually I guess), it would need to be reverted back to `site-packages`.

**Comment by chibill** [comment]
I reinstalled it and it worked. (I must have messed up something.) Also this is a question for another issue but is there away to make pip install the python2 packages to site-packages-2?

**Comment by ywangd** [comment]
You'll have to specified it explicitly, e.g.
```pip install SOME_PACKAGE -d ~/Documents/site-packages-2```

**Comment by chibill** [comment]
Okay. Just asking if there was like a way to set that sort of globally.
