### ISSUE TITLE
Launch via wrench menu executes open editor file

### ISSUE THREAD

**Issue by Dutcho** [ywangd/stash#225]
Pythonista supplies the current editor tab's path as an argument to any command chosen in the wrench menu. This is great if you have e.g. a word counting utility, because that will operate on the file open in the editor.
However, launch_stash executes any command specified as an argument on the command line instead of totd (as of latest change of 23 Oct). This is fine if you start stash by opening launch_stash and selecting run; no arg, no harm done. But if you start stash from the wrench menu (as facilitated by easy_config), it executes the file open in the editor prior to the stash repl. This is usually **NOT** what you want.

**Comment by bennr01** [comment]
Sorry, i forgot that the wrench-action passed the current path to the script. I will try to fix this soon (probably by changing the  'command' argument into a '-r command' argument). Thanks for the bugreport.

**Comment by bennr01** [comment]
@Dutcho Unfortunately, I was unable to reconstruct this bug (does it only occur in the beta?), but I changed the `command`-parameter into a `-c command` parameter, which should fix this bug. However, i am not sure whether this really works (I think `argparse` may throw an exception when another parameter was passed, but if this bug didn't occur before the last change to `launch_stash.py` it should be fine. It works fine for me).
The fix is available in the `restructure` branch in my fork, but it may still take a couple of days before i create a pull-request because a new feature in this branch is still bugged. If you want to test it, use `selfupdate -f bennr01:restructure`. I hope this helps.

**Comment by jsbain** [comment]
One of the recent betas changed how arguments work.  iirc, the wrench menu gets passed the wrenchmenu script name twice.

**Comment by bennr01** [comment]
@jsbain thanks for the information. Unfortunately i don't have access to the beta (i filled the form a few months ago but didn't receive an email, just send another form). Can you test if the fix works? Thanks.

**Comment by Dutcho** [comment]
@bennr01 thanks for following up so quickly.
To test, I self-updated from `restructure` and got a `launch_stash` that produces -c COMMAND in its usage note (as intended). However, when running from the wrench, it produces an error: `unrecognized arguments: /path/to/file/in/editor`, which makes sense as the beta (301012) does pass the path-name and the script doesn't expect that.

An `--ignore`-command may be required in [`launch_stash`](https://gist.github.com/anonymous/dd913c0c870629408ac19bb8f7aa3196), although that will also require [`easy_config`](https://gist.github.com/anonymous/a29992312be2124e966ff3b1323edbf2) to supply that argument and [`pythonista_add_action`](https://gist.github.com/anonymous/9efb55e3da1556e6ad10a5ebfcd5a950) to allow supplying arguments.

**Comment by bennr01** [comment]
@Dutcho thanks for the answer. I could not test the fix because i have no access to the beta.
I expected that this may happen and will try to create another fix soon. `--ignore-command` would solve the problem, but it would require all shortcuts to be recreated manually. I will try to add a `[arg [arg ...]` which will simply ignore all other arguments.

**Comment by bennr01** [comment]
@Dutcho Ok, i created another fix in the `restructure` branch of my fork. `launch_stash.py` will now ignore unknown arguments. To use/test the fix, simply update to the fork again using `selfupdate -f bennr01:restructure`.
