### ISSUE TITLE
Running StaSh commands from external Python file

### ISSUE THREAD

**Issue by Seanld** [ywangd/stash#249]
Say I wanted to create a new bin command, how would I get that Python program to send a call to the StaSh shell to run a specific line/command with arguments? I've been studying the layout of StaSh's files, and I thought I almost had it, but it didn't quite work the way I wanted it to.

**Comment by jsbain** [comment]
You can use `_stash('some commandline with arguments')`

See for example git.py, which uses stash wget etc commands.

**Comment by Seanld** [comment]
Yeah I figured that out by analyzing the whole tree of freaking StaSh files. But anyways, wouldn't I have to modify the actual `launch_stash.py` file in order to call that? Or could I make a call like that from within a `lib` program?

**Comment by bennr01** [comment]
@seanld the `_stash` variable is defined and put in the namespace of every command StaSh executes. You do not need to modify anything for this. Take a look at the source code of the 'crypt' or 'mc' command.
IIRC libs dont have direct access to the stash object. I changed this in a not merged commit.
Also, please make the start of the server disabled by default. StaSh is already pretty slow and takes some time to start. I think making the server a command instead of a lib would be a better idea.
Thanks for your efforts.

**Comment by Seanld** [comment]
@bennr01 thank you!
