### ISSUE TITLE
`pip install incremental` results in TypeError

### ISSUE THREAD

**Issue by glyph** [ywangd/stash#270]
The error is:

```
TypeError('string indices must be integers, not str',)
```

It doesn't show me a full traceback so I don't know how to debug.

**Comment by dgelessus** [comment]
To enable tracebacks for Stash commands, you can run `stashconf py_traceback 1`. There's also `stashconf py_pdb 1` to automatically go into PDB on an exception.

However it's possible that Stash pip simply isn't compatible with `incremental`. Stash pip doesn't use the real `setuptools` and `pip`, it just emulates the most important parts, so anything that relies on advanced `setuptools` features might not work. (Correct me if I'm wrong, I'm not all that familiar with Stash pip's internals.)

**Comment by zrzka** [comment]
@dgelessus you're right. `install` / `update` commands are wrapped with context manager which pops setuptools modules, [fakes them](https://github.com/ywangd/stash/blob/dev/bin/pip.py#L209), issues install / update and then restores them back.

**Comment by glyph** [comment]
I… I know it's not compatible? that's why I filed the bug? :)

**Comment by dgelessus** [comment]
Right, I wasn't saying it's *supposed* to be that way. :) Just wanted to explain that Stash's `pip` is currently a completely different tool than the regular `pip`, so you might find that many advanced features aren't supported yet. I can't help much with fixing this, it's been a while since I worked on Stash, and I didn't work on the `pip` command.

Have you tried using `stashconf py_traceback 1` to enable tracebacks?

**Comment by glyph** [comment]
I tried that and then I did `pip install incremental` but I don't see a traceback.

If you do this in your pythoninsta, does it work?

**Comment by dgelessus** [comment]
OK, it seems that setting `py_traceback` doesn't help here, because `pip` catches and prints the exception itself. After a quick change to make it print the full traceback, this is what I get:

```
[~/Documents]$ pip install incremental
Querying PyPI ... 
Downloading package ...
Opening: https://pypi.python.org/packages/8f/26/02c4016aa95f45479eea37c90c34f8fab6775732ae62587a874b619ca097/incremental-17.5.0.tar.gz
Save as: /private/var/mobile/Containers/Data/Application/988D9C11-8303-4F00-90CA-0AE759911328/tmp//incremental-17.5.0.tar.gz (15527 bytes)
     15527  [100.00%]
Extracting archive file ...
Archive extracted.
Running setup file ...
Traceback (most recent call last):
  File "site-packages/stash/bin/pip.py", line 494, in run
    return ArchiveFileInstaller._run_setup_file(setup_filename)
  File "site-packages/stash/bin/pip.py", line 676, in _run_setup_file
    ep = entry_points[epn]
TypeError: string indices must be integers, not str
Failed to run setup.py
Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.
```

The issue seems to be that `incremental`'s `entry_points` are a string? I didn't even know that was possible, but according to [the Setuptools docs](http://setuptools.readthedocs.io/en/latest/setuptools.html#id21) this is allowed and not deprecated or anything.

**Comment by bennr01** [comment]
@dgelessus Thanks for investigating this. Adding support for entrypoint strings seems rather complicated, so should we just ignore entrypoint definitions as strings? At least until support for entrypoint strings is added?

**Comment by dgelessus** [comment]
@bennr01 The string version of `entry_points` is relatively easy to convert to a dict, using [`pkg_resources.split_sections`](https://github.com/pypa/setuptools/blob/f7ac232981d3d01e3c76890ae28da75859790dbe/pkg_resources/__init__.py#L3076). As far as I can tell, there's no difference between the string and dict formats after conversion.

**Comment by bennr01** [comment]
@dgelessus Thanks :D I will start working on a patch right away.

**Comment by bennr01** [comment]
This is now fixed in [bennr01:entrypoint_improvements](https://github.com/bennr01/stash/tree/entrypoint_improvements), but further testing may be required.
I was able to successfully install `incremental` and `twisted`.

If you want to update to the branch containing the fix, you can:
- **easy way:** Click [this link](pythonista3://launch_stash.py?action=run&args=--command%20%22selfupdate%20-f%20bennr01%3Aentrypoint_improvements%22) on a iOS-Device with pythonista3 and StaSh installed: pythonista3://launch_stash.py?action=run&args=--command%20%22selfupdate%20-f%20bennr01%3Aentrypoint_improvements%22
- **normal way:** start StaSh and run the command `selfupdate -f bennr01:entrypoint_improvements`
