### ISSUE TITLE
Error: Failed to fetch package release urls

### ISSUE THREAD

**Issue by jphoebe4086824** [ywangd/stash#309]
i can't use pip install , it always show 'Error: Failed to fetch package release urls'  but i can use pip search , what happened?

**Comment by nasmatic** [comment]
I met the same problem,and I modified the pip.py file in line 915 , 'http://' to 'https://',it worked.had no idea if this was the reason or it was  just self-healing

**Comment by traindriverrev** [comment]
Thanks for the https thing. My line 915 wasn’t a line with an http reference but somewhere around 921. Altered that. Didn’t work. Found another reference further in. With both altered to https I’ve got it working.

**Comment by traindriverrev** [comment]
@jphoebe4086824 I notie you closed this. But it's still only a workaround isn't it? The problem is not resolved as such.

**Comment by GalvinGao** [comment]
Same problem appeared. Run StaSh on iOS 11.3.1, iPad Pro, latest Pythonista. Not network problem due to good quality of connection to pypi.python.org .

**Comment by SeanMaths4EAL** [comment]
Still doesn't work

**Comment by bennr01** [comment]
@SeanMaths4EAL are you sure your problem is related to this issue?
IIRC, this issue was caused by a PyPI API change, which should have been fixed long ago.

The issue `failed to fetch package release URLs` is most of the time shown when the package you want to install is not found. Are you sure you  have not misspelled the package name?

Please provide the following information:
- name of package you want to install and the pip command you use
- output of `pip --verbose install your_package`
- output of `version`

**Comment by ifuchs** [comment]
I'm getting precisely this problem now. Making this even more strange is (and I must be dropping bits or something) that I was sure this worked an hour ago and that I was even able to import the module but then when I went back the module was gone, and pip stopped working.

$ pip install youtube
Querying PyPI ... 
Error: Failed to fetch package release urls

**Comment by Said779s** [comment]
Anyone knows how to fix it?
