### ISSUE TITLE
Installing azure-storage-queue module

### ISSUE THREAD

**Issue by Uasmi** [ywangd/stash#325]
Hey guys,

Trying to install azure storage queue through pip, but got error with "setup.py missing"

Tried the following suggestion found (with running install_llc.sh from stash) on forum, but seems like I made a mistake somewhere. Here's what install_llc.sh contains, and I run it from stash:

#!/bin/sh
cd ~/Documents
mkdir st_install
cd st_install

wget https://files.pythonhosted.org/packages/2a/16/7b1c6a3250e0eec6c88257a0fc6a376352b108cb1494c628b19802da7dad/azure-storage-queue-1.3.0.tar.gz
tar -vzxf azure-storage-queue-1.3.0.tar.gz

mv azure-storage-queue-1.3.0.tar.gz/azure-storage-queue ~Documents/site-packages

echo 'def get_platform_osx(cvar,osname,release,machine):'> ~/Documents/site-packages/_osx_support.py
echo ' return osname,release,machine' » ~/Documents/site-packages/_osx_support.py
cd ..
rm -rf st_install

Maybe there's some other way to install a module?

**Comment by bennr01** [comment]
> `echo 'def get_platform_osx(cvar,osname,release,machine):'> ~/Documents/site-packages/_osx_support.py
echo ' return osname,release,machine' » ~/Documents/site-packages/_osx_support.py`

Are you sure these commands are correct? I may be wrong, but wont the second line overwrite the first one? This would result in a invalid syntax.
Try to edit `_osx_support.py` in the editor and insert the `def get_platform_osx...` lines manually.
Also, are you sure the file `osx_support.py` is located directly in `site-packages`?
Also, in the newest StaSh, unless you specifiy the `-6` parameter, StaSh pip shopuld install into `site-packages<2|3>` instead of `site-packages`.

BTW, im going to experiment a bit with wheels support for pip, which may fix some issues in the future.

**Comment by Uasmi** [comment]
Fixed it, made a mistake in moving the folders:

#!/bin/sh
cd ~/Documents
mkdir st_install
cd st_install

wget https://files.pythonhosted.org/packages/2a/16/7b1c6a3250e0eec6c88257a0fc6a376352b108cb1494c628b19802da7dad/azure-storage-queue-1.3.0.tar.gz
tar -vzxf azure-storage-queue-1.3.0.tar.gz

mv azure-storage-queue-1.3.0.tar.gz/azure ~Documents/site-packages
mv azure-storage-queue-1.3.0.tar.gz/*.egg-info ~Documents/site-packages

echo 'def get_platform_osx(cvar,osname,release,machine):'> ~/Documents/site-packages/_osx_support.py
echo ' return osname,release,machine' » ~/Documents/site-packages/_osx_support.py
cd ..
rm -rf st_install
