### ISSUE TITLE
Stash function for installing pypi packages.

### ISSUE THREAD

**Issue by briarfox** [ywangd/stash#34]
I like how stash updates and installs the /bin modules by executing a .sh file. I used this to import pyte inside ssh. It would be nice if stash exposed a function to replicate pulling packages off of pypi. I am currently working on a pip module for stash which could be used for this, but it may be better to have an accessable function in stash for it. Here is an example of the function I'm using to impor pyte.

<pre>
def get_pyte():
    import tempfile
    commands = '''
    echo StaSh ssh installing pyte...
    wget https://codeload.github.com/selectel/pyte/zip/master -o ~/Documents/site-packages/pyte.zip
    mkdir ~/Documents/site-packages/pyte_folder
    unzip ~/Documents/site-packages/pyte.zip -d ~/Documents/site-packages/pyte_folder
    rm -r ~/Documents/site-packages/pyte.zip
    mv ~/Documents/site-packages/pyte_folder/pyte ~/Documents/site-packages/
    rm -r ~/Documents/site-packages/pyte_folder
    echo done
    '''
    temp = tempfile.NamedTemporaryFile()
    try:
        temp.write(commands)
        temp.seek(0)
        globals()['_stash'].runtime.exec_sh_file(temp.name)
    finally:
    # Automatically cleans up the file
        temp.close()
</pre>

**Comment by ywangd** [comment]
This issue seems to become two separate ones. The first the covered by the `pip` module (#39) and the second one is to have a command to manage all other commands. 

So for the second issue, the first design comes to mind is as follows:

* A command, lets say its called `scm` (stash command manager)
* An index hosted on GitHub which is a registry for available command scripts. It can be simply just a json file, e.g.:
```Javascript
{
    'awesome_command_name': {
        'url': 'http://.....',  // the url to retrieve the script
        'description': 'texts',
        'installation_instruction': {
            // some APIs published by stash, something like 
            // whether it shall be installed like an pypi package
        }
    },
    'another_awesome_command' : {
        ...
    }
}
```
* Some example usage of scm could be as follows:
 * `scm list`
 * `scm install awesome_command_name`
 * `scm remove awesome_command_name`

Please let me know if above makes sense. If this command is necessary, I'll create a new separate issue for it.

**Comment by briarfox** [comment]
@ywangd That looks like a great way to handle stash scripts. It's like pypi for pythonista-stash. It looks like a very logical way to handle it. It would allow non core stash modules to be hosted in thier developer's repos. Seems like a good solution to me.

**Comment by ywangd** [comment]
New issue #65 created.
