### ISSUE TITLE
"pip install shopifyapi" issue

### ISSUE THREAD

**Issue by kadabra2** [ywangd/stash#378]
please, I try to run >> pip install ShopifyAPI on pythonista using stash, but I am getting the error below:

![58902680-1a6c7080-86f3-11e9-8519-2b8d0bc4a431](https://user-images.githubusercontent.com/14969583/59140386-1ad36880-898c-11e9-83b8-3583654cd93e.jpeg)

Any suggestion please ?

**Comment by bennr01** [comment]
Hi, thanks for the bug report. This is now fixed in 8dda6fcec1370f4325005bbc3456b2f4923c9aaf. This fix is not yet in the main repo, but you can run `selfupdate -f bennr01:yapf` to update to the branch containing the fix. Afterwards, please force-quit pythonista and start StaSh again, otherwise  the changes will not take effect.

**Comment by kadabra2** [comment]
This was very helpful 👍thank you.
