### ISSUE TITLE
pip install troposphere issue 

### ISSUE THREAD

**Issue by mcmans** [ywangd/stash#404]
Hi,

I’m trying to install the troposphere library and it looks like it’s partially installing then failing. I’m assuming on one of the dependencies.

I’ve attached a screenshot. Please let me know if you need more information.

<img width="1024" alt="Screenshot 2020-03-13 at 00 29 01" src="https://user-images.githubusercontent.com/17052665/76578995-88379b00-64c2-11ea-8b3e-90d5aaf7a68b.png">

**Comment by mikaelho** [comment]
Is the install successful on some other platform?

**Comment by bennr01** [comment]
This should now be fixed in b64da1f. Apparently, some packages define their dependencies in `setup.py` as a single string instead of a list of str. Our dependency parser did not handle this case, so it attempted to treat the whole [dependency file](https://github.com/cloudtools/troposphere/blob/master/requirements.txt) as a list of dependencies, taking each byte as a separate dependency.

I'll merge the fix in a few minutes, can you check if it will work then?

Also, congratulations for creating issue #404. Ironically, `pip` could indeed not find the dependencies...

**Comment by mcmans** [comment]
> This should now be fixed in [b64da1f](https://github.com/ywangd/stash/commit/b64da1f86ae63520c79770643acdbe8e71baf1b0). Apparently, some packages define their dependencies in `setup.py` as a single string instead of a list of str. Our dependency parser did not handle this case, so it attempted to treat the whole [dependency file](https://github.com/cloudtools/troposphere/blob/master/requirements.txt) as a list of dependencies, taking each byte as a separate dependency.
> 
> I'll merge the fix in a few minutes, can you check if it will work then?
> 
> Also, congratulations for creating issue #404. Ironically, `pip` could indeed not find the dependencies...
> 
> **EDIT:** It should now be merged into the `dev` branch. To update, use `selfupdate -f dev`.

Yeah that fixed the install of the library, thanks. Although encountered a further issue.

<img width="1024" alt="Screenshot 2020-03-13 at 23 49 04" src="https://user-images.githubusercontent.com/17052665/76669875-897dcc00-6585-11ea-84fa-33f699981f95.png">

**Comment by mikaelho** [comment]
`basestring` points to a Python 2 issue. There are other long-standing Python 2 issues still open for the toposphere project. Do they officially support Python 3?
