### ISSUE TITLE
Check the value of $BIN_PATH

### ISSUE THREAD

**Issue by omelsn** [ywangd/stash#508]
Всем привет хочу запустить свой код на iphone, написанный на компьютере. Установил платную версию Pythonista 3 на iphon, вычитал что для для установки модуле python нужно запустить stash, установил install_StaSh, getstash в консоли пишет Installation completed. Please restart Pythonista.... После этого stash запускается и вылетает, пишет tip: Check the value of BIN_Path i.e.
echo: $BIN_PATH to see where stash loc for comand scripts, что возможно нужна версия 2 питона, делал Python 2 to 3 не помогло, подскажите как заставить работать Pythonista 3 и где вообще находится эта гребаная интерактивная подсказка Pythonista и в какую директорию все ставится где найти lib, site-packages и тд

**Comment by cclauss** [comment]
> Hello everyone, I want to run my code on an iPhone, written on a computer. I installed the paid version of Pythonista 3 on my iPhone, read that to install the Python module you need to run stash, installed install_StaSh, getstash says Installation completed in the console. Please restart Pythonista.... After this stash starts and crashes, writes tip: Check the value of BIN_Path i.e.
echo: $BIN_PATH to see where stash loc for command scripts, that perhaps version 2 of Python is needed, did Python 2 to 3 did not help, tell me how to get Pythonista 3 to work and where is this f___ing Pythonista interactive help located and in what directory everything is put where find lib, site-packages, etc.

`BIN_PATH` is a bad sign that your dependency contains compiled C (or similar) code which iOS is going to reject because it is not digitally signed by the Pythonista digital signature.

What dependencies are you trying to install?

**Comment by omelsn** [comment]
Доброе утро, напишите пожалуйста поподробнее где проверять $BIN_PATH, алгоритм действий «путь по которому находится» данная нстройка

**Comment by omelsn** [comment]
И почему в приложении «Файлы» на своём iphone я не вижу папки Pythonista, lib, site-pakedgest?

**Comment by omelsn** [comment]
Заранее спасибо

**Comment by cclauss** [comment]
## What dependencies are you trying to install?

**Comment by omelsn** [comment]
Как я уже писал я пытаюсь запустить свой код который я написал на компьютере для этого мне нужны модули dlib CMake face_recognition, numpy pandas

**Comment by cclauss** [comment]
Scroll to the bottom of https://github.com/davisking/dlib

Dlib and CMake are written in C/C++ so (as I have already written) iOS will not allow them to run unless they are built into Pythonista.

Numpy and Pandas are built into Pythonista.
