### ISSUE TITLE
git checkout being destructive

### ISSUE THREAD

**Issue by dgelessus** [ywangd/stash#91]
Something "fun" just happened when I was going to commit `open.py` to my StaSh fork...

```shell
$ git branch
dev
* master
# wait, wrong branch...
$ git checkout dev
$ git add bin/open.py
$ git status
(no changes)
# what?
$ edit bin/open.py
File not found.
# crap.
$ git checkout master
$ edit bin/open.py
File not found.
# brb, gotta rewrite some code from scratch.
```

~~Should `git checkout` maybe warn about untracked files that could get deleted, or was I just mentally absent enough to not think of this (admittedly kind of obvious) behavior?~~

PS: Just checked, this is *definitely* not supposed to happen. The real problem seems to be that `bin/open.py` was not correctly recognized as untracked, so it got lost during checkout. On my Mac Git recognizes `bin/open.py` as untracked and keeps it when I checkout another branch.

PPS: Or perhaps `git checkout` shouldn't [delete all untracked files](https://github.com/ywangd/stash/blob/master/bin/git.py#L326).

**Comment by jsbain** [comment]
Uhh yeah.  I had this fixed in gitview, guess I never ported it back to git.py.
In gitview I added several warnings on "dangerous" commands like switching branches with uncommitted changes.  (notice also line 337: don't ever make changes, then decide you want to create a new branch!).  git.py really needs an overhaul -- I'd like to basically start over, and add in many of the git commands with the behavior matching the real git.  There are still some dangerous and nonintuitive behavior right now (such as push will happily overwrite a non-ancestor branch... this is why gitview disappeared last week)

**Comment by ywangd** [comment]
@jsbain If you are going to start over, how feasible it is to use just dulwich? As I understand it, gittle is a high-level wrapper of dulwich. So in theory, gittle is not irreplaceable? I am saying this because I remember you said there were some incompatibility issues between different versions of dulwich and gittle so you had to make some custom patches. If the dependancy to gittle can be dropped, would it be possible that you can make use of the latest official dulwich release instead of custom patching?

**Comment by jsbain** [comment]
In retrospect, I'm not sure why transistor1 modified dulwich in the first place.  I recently merged the official release back into his fork, and the remaining changes are not really important.  I plan on using the official version again soon, but this will introduce a backwards incompatibility issue with shellista.  

Gittle is just a wrapper over dulwich, as you say.  There is a lot of overlap now that dulwich has a porcelain module, but Gittle does has some nice convenience methods that I'd rather not code from scratch.  
I've got two patches on gittle right now:  1) removed thin-pack support, since this seemed to be causing problems.  I need to re-investigate this some more, since technically thin-packs should be supported
  2) there was a bug in diff_changes_paths.  That probably should be an upstream pull request.

**Comment by jsbain** [comment]
https://github.com/ywangd/stash/commit/74aa3712fc4e54a6c55aba5a648edafcebcecd39

**Comment by jsbain** [comment]
One note, be advised that checkout does not currently reload the current file in the editor. 
 And the editor doesn't seem to know it has to write back to disk when you change the file from underneath it... So this can lead to confusion where you have an old version of a file stuck.  Opening a different file fixes this issue.   

This commit has some protections when there are uncommitted changes against tracked files.  
Also, reset is actually functional, allowing you to stage changes from other commits (or revert any currently staged back to a previous commit), or, using the hard command, will let you check out single files from other commits I to the working area.  Useful for rebasing ...
